name: Build PDF Viewer for Windows

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build vPDF.exe
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --windowed --clean --name vPDF --icon=pdf.ico main.py

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: vPDF-Windows
          path: dist/vPDF.exe

      - name: Upload to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/vPDF.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}